@extends('layouts.app')

@section('pageTitle', 'Accueil')
@section('pageDescription', 'Webzine communautaire des séries TV - Critiques et actualité des séries tv, notez et laissez vos avis sur les derniers épisodes, créez votre planning ...')

@section('content')
    <div class="fifteen wide column">
        <div class="ui segment">
            <div class="ui active dimmer tempDimmer">
                <div class="ui large text loader">En cours de réalisation</div>
            </div>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus dolores facilis hic id, inventore iure iusto magni necessitatibus nemo nobis reprehenderit repudiandae rerum similique suscipit tenetur ut vel voluptate voluptatum.</span><span>Autem dolor fugit quae qui reiciendis vel. Adipisci architecto dignissimos dolor ea enim in, maiores nam obcaecati quam, quia quidem quos rerum soluta! Ab accusamus, at cum doloremque pariatur sunt.</span><span>Ab adipisci assumenda dolorem iste nobis nostrum quia sed sequi. Aliquid asperiores blanditiis, cupiditate dolorem eaque fuga fugiat inventore maxime nam necessitatibus nemo obcaecati quibusdam quidem recusandae similique, tempora vel.</span><span>Ab atque autem, blanditiis cum cumque dignissimos dolorem doloremque error eum eveniet ex fuga impedit itaque magnam, maiores neque non perferendis quidem sit suscipit tempora tenetur velit, voluptates. Eligendi, nulla?</span><span>Aperiam doloribus esse est quisquam reiciendis. Culpa cupiditate eligendi et illum impedit iure placeat provident quam veniam vitae? Ducimus, laborum veritatis! Alias corporis, eligendi inventore odit quae sapiente voluptates? Distinctio!</span></p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores culpa distinctio dolore error est exercitationem hic itaque nobis, omnis praesentium quidem rem. Accusamus deserunt ipsam molestiae omnis, quas qui temporibus!</span><span>Aut consequatur consequuntur natus obcaecati similique. Aspernatur delectus, distinctio dolor dolorem doloremque dolores eveniet expedita illo in ipsum iusto minima minus mollitia numquam omnis, perferendis reiciendis repudiandae rerum unde vitae?</span><span>Beatae ea iusto rem sapiente suscipit. Assumenda delectus quo reiciendis sint. A, alias aperiam commodi debitis excepturi minus necessitatibus nesciunt odit perspiciatis! Commodi cum dolore enim eos laborum, quisquam sequi?</span><span>Accusamus accusantium explicabo, laboriosam minima, officiis pariatur possimus praesentium quam quas quia, quo reprehenderit saepe similique sunt ullam. Est expedita ipsum quod rerum! Asperiores cum esse fugiat itaque magni natus!</span><span>Accusamus accusantium, aliquam asperiores aspernatur aut consequatur culpa debitis doloribus enim esse, excepturi fugit laudantium magni maxime, nemo nisi obcaecati perspiciatis placeat praesentium rem sed unde ut voluptatibus. Excepturi, molestiae.</span><span>Aliquam architecto beatae corporis cum earum, eos eum expedita inventore ipsam laboriosam magnam nam non optio qui quia quisquam rerum sed sunt tenetur voluptatibus? Alias ipsam iste minus quae tempora?</span></p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate dolorem ea error inventore maxime molestias quis velit. Consectetur, consequatur cupiditate earum hic itaque laboriosam mollitia neque numquam provident tempore voluptatibus!</span><span>Ab consequuntur, error facere fugit harum illo iure magni minima nam natus odit perspiciatis quae qui quia recusandae rerum sit sunt veniam voluptate voluptates. Ad aut exercitationem facilis laudantium repudiandae.</span><span>Accusamus debitis id illum inventore itaque, libero minima minus nam necessitatibus optio quaerat quidem sit, ut. Amet aperiam culpa doloremque inventore iusto molestias, pariatur quas quidem reiciendis, rerum sit, voluptas!</span><span>Atque cum debitis deserunt dolorem doloremque, error exercitationem facilis fugit laudantium maiores modi nobis nostrum numquam optio praesentium quisquam quos rem, ullam veniam vero. Eligendi, et, quisquam? Corporis, expedita, obcaecati!</span></p>
        </div>
    </div>
@endsection
